/**
 * Golden-fixture regeneration (plan todo 18).
 * Run via `pnpm gen-fixtures` (sets RH_NET_TESTS=1 and RH_GEN_FIXTURES=1).
 * Downloads/reuses the pinned d8-debug canary, generates the big() sample,
 * captures REAL --print-bytecode / --trace-deopt output, prepends a
 * generator-version header, and overwrites the committed fixtures.
 */
import { execFile } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { installEngine } from '../../../apps/main/src/binaries/engine-downloader.js';

const RUN = process.env['RH_GEN_FIXTURES'] === '1' && process.env['RH_NET_TESTS'] === '1';
const execFileP = promisify(execFile);

let dir = '';
let d8 = '';

const BIG_SOURCE_LINES: string[] = [
  'function big(s){',
  'let t = s | 0;'
  // body rows appended programmatically below
];

beforeAll(async () => {
  if (!RUN) return;
  dir = await mkdtemp(join(tmpdir(), 'rh-genfix-'));
  process.env['RH_CACHE_ROOT'] = dir;
  const dbg = await installEngine({ engineId: 'd8-debug' });
  d8 = join(dbg.entry.installedPath ?? '', 'd8.exe');
});

afterAll(() => {
  delete process.env['RH_CACHE_ROOT'];
});

describe.skipIf(!RUN)('fixture regeneration (network)', () => {
  it('regenerates bytecode + deopt goldens from the real binary', async () => {
    const body = ['let t = s | 0;'];
    for (let i = 0; i < 120; i++) {
      body.push(`t = (t + ${i}) ^ (${i} * 3);`);
      body.push('if (t > 1000000000) { t = t >>> 1; }');
    }
    BIG_SOURCE_LINES.push(...body, 'return t; }', 'big(7);');

    const bigFile = join(dir, 'big-sample.mjs');
    await writeFile(bigFile, BIG_SOURCE_LINES.join('\n'), 'utf8');
    const bc = await execFileP(d8, ['--print-bytecode', '--print-bytecode-filter=big', bigFile]);
    const header = `// generator: d8-debug canary, V8 version observed at generation time\n// regenerate: pnpm gen-fixtures\n`;
    await writeFile(join(__dirname, '..', 'fixtures', 'v8-bytecode-big.golden.txt'), `${header}${bc.stdout}`, 'utf8');

    const deoptSource = [
      'function f(x) { return x + 1; }',
      '%PrepareFunctionForOptimization(f);',
      'f(1); f(2);',
      '%OptimizeFunctionOnNextCall(f);',
      'f(3);',
      'f({ valueOf() { return 9; } });'
    ].join('\n');
    const deoptFile = join(dir, 'deopt-sample.mjs');
    await writeFile(deoptFile, deoptSource, 'utf8');
    const deopt = await execFileP(d8, ['--allow-natives-syntax', '--trace-deopt', deoptFile]);
    await writeFile(
      join(__dirname, '..', 'fixtures', 'v8-deopt.golden.txt'),
      `${header}${deopt.stdout}`,
      'utf8'
    );

    expect(bc.stdout).toContain('generated bytecode');
  }, 600_000);
});
