/**
 * Tolerant V8 bytecode parser (plan todo 18, TDD).
 *
 * Input: verbatim `d8 --print-bytecode` output (any recent version family).
 * Blocks start at `[generated bytecode for function: <name> ...]` — V8 ≥13
 * appends a SharedFunctionInfo pointer after the name, which we strip.
 * Anything unparseable is preserved as rawLines (nearest block, else the
 * preamble) — this parser NEVER throws on malformed input.
 */

export interface ParsedInstruction {
  readonly offset: number;
  readonly bytecode: string;
  readonly operands: string[];
  /** Source-position markers (S>/E>) when present on the row. */
  readonly sourceHint?: string;
}

export interface ParsedBytecodeFunction {
  readonly name: string;
  readonly parameterCount: number | null;
  readonly registerCount: number | null;
  readonly frameSize: number | null;
  readonly instructions: ParsedInstruction[];
  readonly constantPool: string[];
  readonly handlerTable: string[];
  /** Unparsed lines that belonged to this block (tolerance channel). */
  readonly rawLines: string[];
}

export interface NormalizedBytecode {
  readonly functions: ParsedBytecodeFunction[];
  /** Lines seen before any block header. */
  readonly preambleRaw: string[];
}

const HEADER_RE = /^\[generated bytecode for function:\s*(.*?)\]\s*$/;
const SFI_TAIL_RE = /\s*\(0x[0-9a-fA-F]+.*$/;
const INSTRUCTION_RE = /^\s*(?:(S>|E>)\s*)?(0x[0-9a-fA-F]+)\s+@\s*(\d+)\s*:\s*(.+)$/;
const HEX_PAIR_RE = /^[0-9a-fA-F]{2}$/;
const PARAM_RE = /^Parameter count:?\s*(\d+)/;
const REGISTER_RE = /^Register count:?\s*(\d+)/;
const FRAME_RE = /^Frame size:?\s*(\d+)/;
const CONST_POOL_RE = /^Constant pool \(size = (\d+)\)/;
const HANDLER_RE = /^Handler Table \(size = (\d+)\)/;

function cleanName(rawHeaderName: string): string {
  return rawHeaderName.replace(SFI_TAIL_RE, '').trim();
}

function splitInstruction(rest: string): { bytecode: string; operands: string[] } {
  const tokens = rest.trim().split(/\s+/);
  const byteTokens: string[] = [];
  let i = 0;
  while (i < tokens.length && HEX_PAIR_RE.test(tokens[i] ?? '')) {
    byteTokens.push(tokens[i] as string);
    i++;
  }
  void byteTokens; // raw byte column is display-only; operands carry semantics
  const remainder = tokens.slice(i).join(' ');
  const spaceAt = remainder.indexOf(' ');
  if (spaceAt === -1) return { bytecode: remainder, operands: [] };
  return {
    bytecode: remainder.slice(0, spaceAt),
    operands: remainder
      .slice(spaceAt + 1)
      .split(/\s+/)
      .filter((t) => t !== '')
  };
}

export function parseV8Bytecode(input: string): NormalizedBytecode {
  const functions: ParsedBytecodeFunction[] = [];
  const preambleRaw: string[] = [];

  let current: {
    name: string;
    parameterCount: number | null;
    registerCount: number | null;
    frameSize: number | null;
    instructions: ParsedInstruction[];
    constantPool: string[];
    handlerTable: string[];
    rawLines: string[];
    section: 'header' | 'instructions' | 'constantPool' | 'handlerTable' | 'other';
  } | null = null;

  const closeCurrent = (): void => {
    if (current !== null) functions.push(current);
    current = null;
  };

  for (const rawLine of input.split(/\r?\n/)) {
    const line = rawLine.replace(/\r$/, '');
    if (line.trim() === '') continue;

    const header = HEADER_RE.exec(line);
    if (header !== null) {
      closeCurrent();
      current = {
        name: cleanName(header[1] ?? ''),
        parameterCount: null,
        registerCount: null,
        frameSize: null,
        instructions: [],
        constantPool: [],
        handlerTable: [],
        rawLines: [],
        section: 'header'
      };
      continue;
    }

    if (current === null) {
      preambleRaw.push(line);
      continue;
    }

    const param = PARAM_RE.exec(line);
    if (param) {
      current.parameterCount = Number(param[1]);
      continue;
    }
    const registers = REGISTER_RE.exec(line);
    if (registers) {
      current.registerCount = Number(registers[1]);
      continue;
    }
    const frame = FRAME_RE.exec(line);
    if (frame) {
      current.frameSize = Number(frame[1]);
      current.section = 'instructions';
      continue;
    }
    const pool = CONST_POOL_RE.exec(line);
    if (pool) {
      current.section = 'constantPool';
      current.constantPool.push(`Constant pool (size = ${pool[1] ?? ''})`);
      continue;
    }
    const handler = HANDLER_RE.exec(line);
    if (handler) {
      current.section = 'handlerTable';
      current.handlerTable.push(`Handler Table (size = ${handler[1] ?? ''})`);
      continue;
    }

    if (current.section === 'constantPool') {
      current.constantPool.push(line);
      continue;
    }
    if (current.section === 'handlerTable') {
      current.handlerTable.push(line);
      continue;
    }

    const instruction = INSTRUCTION_RE.exec(line);
    if (instruction) {
      const sourceHint = instruction[1];
      const offset = Number(instruction[3]);
      const tail = instruction[4] ?? '';
      // Rows embed hex-address prefix inside the tail too (e.g.
      // "0x14f... @ 4 : ..." handled above); strip an address@offset echo and
      // the raw byte column before naming the opcode.
      const withoutLoc = tail.replace(/^0x[0-9a-fA-F]+\s*/, '').replace(/^\d+\s*:?\s*/, '');
      const parsed = splitInstruction(withoutLoc);
      current.instructions.push({
        offset,
        bytecode: parsed.bytecode,
        operands: parsed.operands,
        ...(sourceHint !== undefined ? { sourceHint } : {})
      });
      continue;
    }

    // Unknown line → tolerance channel for THIS block.
    current.rawLines.push(line);
  }

  closeCurrent();
  return { functions, preambleRaw };
}
