/**
 * Golden-fixture tests (plan todo 18): fixtures were generated by the REAL
 * downloaded d8-debug canary 15.4.45 during QA (see generator-version headers
 * inside each file). Regenerate via `pnpm gen-fixtures` with RH_NET_TESTS=1.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseV8Bytecode } from './v8-bytecode.js';
import { parseV8Deopts } from './v8-deopt.js';

function fixture(name: string): string {
  // vitest's virtual module graph makes __dirname unreliable across ESM/CJS;
  // tests always run with repo-root cwd, so anchor there.
  return readFileSync(join(process.cwd(), 'packages', 'engine-parsers', 'fixtures', name), 'utf8');
}

describe('parseV8Bytecode — real d8-debug 15.4.45 golden', () => {
  const input = fixture('v8-bytecode-big.golden.txt');

  it('finds the big() block with ≥200 instructions', () => {
    const parsed = parseV8Bytecode(input);
    const big = parsed.functions.find((f) => f.name === 'big');
    expect(big).toBeDefined();
    if (!big) return;
    expect(big.instructions.length).toBeGreaterThanOrEqual(200);
    // V8 counts the receiver: big(s) → parameter count 2.
    expect(big.parameterCount).toBe(2);
    expect(big.registerCount).not.toBeNull();
    expect(big.frameSize).not.toBeNull();
  });

  it('extracts opcode + operands + offsets for representative rows', () => {
    const parsed = parseV8Bytecode(input);
    const big = parsed.functions.find((f) => f.name === 'big');
    if (!big) throw new Error('missing big()');
    const bitOr = big.instructions.find((i) => i.bytecode === 'BitwiseOrSmi');
    expect(bitOr?.operands.length ?? 0).toBeGreaterThan(0);
    const first = big.instructions[0];
    expect(typeof first?.offset).toBe('number');
    expect(first!.bytecode.length).toBeGreaterThan(0);
    expect(first!.bytecode).toMatch(/^[A-Za-z]/); // opcode, not hex bytes
  });

  it('captures constant pool lines when present', () => {
    const parsed = parseV8Bytecode(input);
    const anyPool = parsed.functions.some((f) => f.constantPool.length > 0);
    expect(anyPool).toBe(true);
  });
});

describe('parseV8Bytecode — truncated/garbage tolerance', () => {
  it('returns partial functions + rawLines without throwing', () => {
    const parsed = parseV8Bytecode(fixture('v8-bytecode-truncated.golden.txt'));
    expect(parsed.functions.length).toBe(1);
    const cut = parsed.functions[0];
    expect(cut?.name).toBe('cut');
    expect(cut?.parameterCount).toBe(2);
    // One fully-valid row plus a best-effort row whose byte column is
    // unreadable ('??') — both survive; nothing throws.
    expect(cut?.instructions.length).toBe(2);
    const second = cut?.instructions[1];
    expect(second?.bytecode).toBe('??');
    expect(cut?.rawLines.join('\n')).toContain('complete garbage');
  });
});

describe('parseV8Deopts — real d8-debug 15.4.45 golden', () => {
  it('extracts kind/reason/function/offset from the bailout line', () => {
    const deopts = parseV8Deopts(fixture('v8-deopt.golden.txt'));
    expect(deopts.length).toBeGreaterThanOrEqual(1);
    const first = deopts[0];
    expect(first?.kind).toContain('deopt');
    expect(first?.reason).toBe('not a Smi');
    expect(first?.functionName).toBe('f');
    expect(first?.bytecodeOffset).toBeTypeOf('number');
  });

  it('returns empty array for non-deopt output (no throw)', () => {
    expect(parseV8Deopts('hello\nworld\n')).toEqual([]);
  });
});
