/**
 * Compare-engines state (plan todo 26): fans out the same snippet to
 * multiple engines, collects per-engine results, and exports markdown.
 * Engine terminology mapping lives here (renderer-safe, no engine internals).
 */
import { create } from 'zustand';
import type { AnalysisResult } from '@rh/protocol';

export interface EngineTerminology {
  readonly id: string;
  readonly displayName: string;
  readonly bytecodeLabel: string;
}

export const ENGINE_TERMINOLOGY: Record<string, EngineTerminology> = {
  v8: { id: 'v8', displayName: 'V8', bytecodeLabel: 'Ignition bytecode' },
  spidermonkey: { id: 'spidermonkey', displayName: 'SpiderMonkey', bytecodeLabel: 'dis() bytecode + source notes' },
  javascriptcore: { id: 'javascriptcore', displayName: 'JavaScriptCore', bytecodeLabel: 'LLInt / generated bytecode' }
};

export function terminologyFor(engineId: string): EngineTerminology {
  return ENGINE_TERMINOLOGY[engineId] ?? { id: engineId, displayName: engineId, bytecodeLabel: 'bytecode' };
}

export interface CompareEntry {
  engineId: string;
  version: string | null;
  status: 'idle' | 'running' | 'done' | 'unsupported' | 'error';
  reason: string | null;
  rawOutput: string;
}

interface CompareState {
  entries: CompareEntry[];
  running: boolean;
  selectedEngines: string[];
  toggleEngine: (id: string) => void;
  startCompare: (code: string) => Promise<void>;
  cancelCompare: () => void;
  exportMarkdown: () => string;
}

let seq = 0;

export const useCompare = create<CompareState>((set, get) => ({
  entries: [],
  running: false,
  selectedEngines: ['v8', 'd8-debug'],
  toggleEngine: (id) =>
    set((s) => ({
      selectedEngines: s.selectedEngines.includes(id)
        ? s.selectedEngines.filter((x) => x !== id)
        : [...s.selectedEngines, id]
    })),
  startCompare: async (code) => {
    if (!window.api?.analyze || get().running) return;
    const engines = get().selectedEngines;
    if (engines.length < 2) return;
    set({ running: true, entries: engines.map((id) => ({ engineId: id, version: null, status: 'running' as const, reason: null, rawOutput: '' })) });

    const requestIdBase = `cmp-${Date.now()}`;
    // Track requestId -> engineId for event routing
    const pending = new Map<string, string>();
    const off = window.api.onAnalysisEvent((event) => {
      const eng = pending.get(event.requestId);
      if (!eng) return;
      if (event.t === 'result' && event.result) {
        const text = (event.result as { text?: string }).text ?? JSON.stringify(event.result).slice(0, 2000);
        set((s) => ({
          entries: s.entries.map((e) => (e.engineId === eng ? { ...e, status: 'done' as const, rawOutput: text } : e))
        }));
      } else if (event.t === 'error' || event.t === 'unsupported') {
        const reason = (event as { reason?: string; message?: string }).reason ?? (event as { message?: string }).message ?? 'failed';
        set((s) => ({
          entries: s.entries.map((e) => (e.engineId === eng ? { ...e, status: event.t as 'error' | 'unsupported', reason } : e))
        }));
      } else if (event.t === 'done') {
        set((s) => ({
          entries: s.entries.map((e) => (e.engineId === eng && e.status === 'running' ? { ...e, status: 'done' as const } : e))
        }));
      }
    });
    const promises = engines.map(async (engineId) => {
      const requestId = `${requestIdBase}-${engineId}`;
      pending.set(requestId, engineId);
      try {
        await window.api.analyze({
          requestId,
          engineId: engineId as 'v8' | 'd8-debug' | 'spidermonkey' | 'javascriptcore',
          code,
          analysisTypes: ['bytecode'],
          timeoutMs: 30_000
        });
      } catch {
        set((s) => ({
          entries: s.entries.map((e) =>
            e.engineId === engineId ? { ...e, status: 'error' as const, reason: 'dispatch failed' } : e
          )
        }));
      }
    });
    await Promise.all(promises);
    // Give engines time to stream results, then cleanup
    setTimeout(() => {
      off();
      set({ running: false });
    }, 8000);
  },
  cancelCompare: () => set({ running: false }),
  exportMarkdown: () => {
    const { entries } = get();
    const lines: string[] = ['# Engine Comparison', ''];
    for (const entry of entries) {
      const term = terminologyFor(entry.engineId);
      lines.push(`## ${term.displayName} (${entry.engineId})`);
      lines.push('');
      if (entry.rawOutput !== '') {
        lines.push('```');
        lines.push(entry.rawOutput.slice(0, 2000));
        lines.push('```');
      } else {
        lines.push('_no result_');
      }
      lines.push('');
    }
    return lines.join('\n');
  }
}));
