import { describe, expect, it } from 'vitest';
import {
  AnalysisRequestSchema,
  AnalysisResultSchema,
  BinaryManifestSchema,
  EngineCapabilitiesSchema,
  IPC,
  PingRequestSchema,
  PingResponseSchema,
  RunEventSchema,
  RunRequestSchema,
  RunResultSchema,
  RuntimeCapabilitiesSchema
} from './index.js';

const sha = 'a'.repeat(64);

describe('protocol ping contract', () => {
  it('round-trips a valid ping request', () => {
    const req = { sentAt: Date.now() };
    expect(PingRequestSchema.parse(req)).toEqual(req);
  });

  it('round-trips a valid ping response', () => {
    const res = { pong: true as const, receivedAt: Date.now(), echoSentAt: Date.now() };
    expect(PingResponseSchema.parse(res)).toEqual(res);
  });

  it('rejects malformed payloads', () => {
    expect(() => PingRequestSchema.parse({ sentAt: 'not-a-number' })).toThrow();
    expect(() => PingResponseSchema.parse({ pong: false })).toThrow();
    expect(() => PingResponseSchema.parse({ pong: true, receivedAt: 'x', echoSentAt: 1 })).toThrow();
  });

  it('exposes the canonical channel name', () => {
    expect(IPC.ping).toBe('app:ping');
  });
});

describe('run contract', () => {
  const baseReq = {
    runId: 'run-12345678',
    workspaceId: 'ws1',
    entryPath: 'C:\\w\\entry.cjs',
    runtimeId: 'node' as const,
    runtimeVersion: '22.17.0',
    timeoutMs: 5000,
    cwd: 'C:\\w'
  };

  it('round-trips RunRequest', () => {
    expect(RunRequestSchema.parse(baseReq)).toEqual(baseReq);
  });

  it('rejects RunRequest with bad runtime or nonpositive timeout', () => {
    expect(() => RunRequestSchema.parse({ ...baseReq, runtimeId: 'browser' })).toThrow();
    expect(() => RunRequestSchema.parse({ ...baseReq, timeoutMs: 0 })).toThrow();
  });

  it('round-trips every RunEvent variant', () => {
    expect(RunEventSchema.parse({ type: 'stdout', runId: 'r1', data: 'hi' }).type).toBe('stdout');
    expect(RunEventSchema.parse({ type: 'stderr', runId: 'r1', data: 'boom' }).type).toBe('stderr');
    expect(
      RunEventSchema.parse({
        type: 'result', runId: 'r1', index: 0,
        value: { t: 'map', size: 1, children: [{ k: 'a', node: { t: 'number', prim: '1' } }] }
      }).type
    ).toBe('result');
    expect(
      RunEventSchema.parse({ type: 'exit', runId: 'r1', code: 0, signal: null, durationMs: 12, killedBy: null }).type
    ).toBe('exit');
    expect(RunEventSchema.parse({ type: 'error', runId: 'r1', message: 'x', code: 'ENOENT' }).type).toBe('error');
  });

  it('rejects unknown RunEvent types and circular-value nodes without ref fields', () => {
    expect(() => RunEventSchema.parse({ type: 'wat', runId: 'r1' })).toThrow();
    expect(() =>
      RunResultSchema.parse({ runId: 'r1', status: 'nope', exitCode: 0, durationMs: 1, reports: [] })
    ).toThrow();
  });
});

describe('analysis contract', () => {
  it('round-trips capabilities', () => {
    const rc = {
      supportsTypeScriptNative: false, supportsNpm: true, supportsCommonJS: true,
      supportsESM: true, supportsInspector: true, supportsProfiling: true, supportsHeapSnapshot: true
    };
    expect(RuntimeCapabilitiesSchema.parse(rc)).toEqual(rc);
    const ec = {
      astDump: true, bytecodeDump: true, optCodeDisasm: false, irGraphDump: true,
      deoptTrace: true, gcLog: true, profileSampling: false, perFunctionFilter: true,
      notes: ['--print-ast requires debug build']
    };
    expect(EngineCapabilitiesSchema.parse(ec)).toEqual(ec);
  });

  it('round-trips AnalysisRequest and rejects empty analysisTypes', () => {
    const req = { requestId: 'req-12345678', code: 'function f(){}', analysisTypes: ['bytecode' as const] };
    expect(AnalysisRequestSchema.parse(req)).toEqual(req);
    expect(() => AnalysisRequestSchema.parse({ ...req, analysisTypes: [] })).toThrow();
  });

  it('round-trips AnalysisResult with artifacts + metadata', () => {
    const res = {
      source: 'f', engine: 'v8' as const, engineVersion: '15.4.44', analysisType: 'bytecode' as const,
      rawOutput: '[generated bytecode for function: f]',
      artifacts: [{ name: 'turbo-0.json', path: 'C:\\tmp\\turbo-0.json' }],
      metadata: { flagsUsed: ['--print-bytecode'], durationMs: 120, binaryPath: 'C:\\cache\\d8.exe' }
    };
    expect(AnalysisResultSchema.parse(res)).toEqual(res);
    expect(() => AnalysisResultSchema.parse({ ...res, engine: 'spidermonkeyX' })).toThrow();
  });
});

describe('manifest contract', () => {
  const entry = {
    kind: 'engine' as const,
    id: 'd8-dbg',
    platform: 'win64' as const,
    arch: 'x64' as const,
    version: '15.4.44',
    url: 'https://storage.googleapis.com/chromium-v8/official/canary/v8-win64-dbg-15.4.44.zip',
    sha256: sha,
    license: 'BSD-style (V8)',
    source: 'official-canary' as const,
    customBuildRequired: false as const
  };

  it('round-trips a manifest', () => {
    expect(BinaryManifestSchema.parse({ schemaVersion: 1, entries: [entry] }).entries.length).toBe(1);
  });

  it('rejects bad sha256 / platform / url', () => {
    expect(() => BinaryManifestSchema.parse({ schemaVersion: 1, entries: [{ ...entry, sha256: 'zz' }] })).toThrow();
    expect(() => BinaryManifestSchema.parse({ schemaVersion: 1, entries: [{ ...entry, platform: 'win32' }] })).toThrow();
    expect(() => BinaryManifestSchema.parse({ schemaVersion: 1, entries: [{ ...entry, url: 'not-a-url' }] })).toThrow();
  });
});

