/**
 * AnalysisManager unit tests (plan todo 19): per-type partial success,
 * unsupported degradation, cancellation between types. Real binaries are
 * covered in v8-adapter.net.test.ts.
 */
import { describe, expect, it } from 'vitest';
import type { AnalysisEvent, AnalysisRequest, AnalysisResult, AnalysisType, EngineCapabilities } from '@rh/protocol';
import { AnalysisManager } from './analysis-manager.js';
import { CapabilityGateError } from './v8-adapter.js';

const FULL_CAPS: EngineCapabilities = {
  astDump: true,
  bytecodeDump: true,
  optCodeDisasm: true,
  irGraphDump: true,
  deoptTrace: true,
  gcLog: true,
  profileSampling: true,
  perFunctionFilter: true,
  notes: []
};

interface Harness {
  events: AnalysisEvent[];
  manager: AnalysisManager;
}

function makeManager(opts: {
  binaryFound?: boolean;
  analyzeImpl: (types: AnalysisType[]) => Promise<AnalysisResult[]>;
}): Harness {
  const events: AnalysisEvent[] = [];

  const registry = {
    describe: async () => ({
      id: 'd8-debug' as const,
      version: opts.binaryFound === false ? null : '15.4.45',
      binaryPath: opts.binaryFound === false ? null : 'C:/fake/d8.exe',
      capabilities: opts.binaryFound === false ? null : FULL_CAPS,
      reason: opts.binaryFound === false ? 'not installed' : null
    }),
    capabilities: async () => FULL_CAPS
  };

  let first = true;
  const manager = new AnalysisManager({
    registry: registry as never,
    emit: (e) => events.push(e),
    createAdapter: () => ({
      analyze: async (req: AnalysisRequest & { binaryPath: string }) => {
        if (first) {
          first = false;
        }
        return await opts.analyzeImpl(req.analysisTypes as AnalysisType[]);
      }
    }) as never
  });
  return { events, manager };
}

const REQ_BASE = {
  requestId: 'req-aaaaaaa1',
  engineId: 'd8-debug' as const,
  code: 'function sum(){}',
  timeoutMs: 5000
};

describe('AnalysisManager', () => {
  it('streams results per type then done', async () => {
    const result: AnalysisResult = {
      source: 'x',
      engine: 'v8',
      engineVersion: '15',
      analysisType: 'bytecode',
      rawOutput: '[generated bytecode]',
      artifacts: [],
      metadata: { flagsUsed: ['--print-bytecode'], durationMs: 3, binaryPath: 'C:/fake/d8.exe' }
    };
    const h = makeManager({ binaryFound: true, analyzeImpl: async () => [result] });
    await h.manager.start({ ...REQ_BASE, analysisTypes: ['bytecode'] });

    expect(h.events.filter((e) => e.t === 'result').length).toBe(1);
    expect(h.events.at(-1)?.t).toBe('done');
  });

  it('degrades gated types to unsupported and continues remaining types', async () => {
    const attempted: string[] = [];
    const h = makeManager({
      binaryFound: true,
      analyzeImpl: async (types) => {
        attempted.push(...types);
        if (types[0] === 'optcode') throw new CapabilityGateError('optcode', 'optCodeDisasm');
        return [
          {
            source: 'x',
            engine: 'v8',
            engineVersion: '15',
            analysisType: types[0] ?? 'gc',
            rawOutput: 'ok',
            artifacts: [],
            metadata: { flagsUsed: [], durationMs: 1, binaryPath: 'b' }
          }
        ];
      }
    });

    await h.manager.start({ ...REQ_BASE, analysisTypes: ['optcode', 'gc'] });

    const kinds = h.events.map((e) => e.t);
    expect(kinds).toContain('unsupported');
    expect(h.events.some((e) => e.t === 'unsupported' && e.analysisType === 'optcode')).toBe(true);
    expect(attempted).toContain('gc'); // continued after the gate failure
    expect(h.events.at(-1)?.t).toBe('done');
  });

  it('reports missing binaries with error + done and never spawns', async () => {
    const h = makeManager({ binaryFound: false, analyzeImpl: async () => [] });
    await h.manager.start({ ...REQ_BASE, analysisTypes: ['bytecode'] });
    expect(h.events[0]?.t).toBe('error');
    expect(h.events.at(-1)?.t).toBe('done');
  });

  it('cancel stops subsequent types and emits cancelled', async () => {
    const attempted: string[] = [];
    let astStarted = false;
    let releaseAst: () => void = () => {};
    const astGate = new Promise<void>((r) => {
      releaseAst = r;
    });

    const h = makeManager({
      binaryFound: true,
      analyzeImpl: async (types) => {
        if (types[0] === 'ast') {
          astStarted = true;
          await astGate; // hold the first type open
          return [];
        }
        attempted.push(types[0] ?? '');
        return [];
      }
    });

    void h.manager.start({ ...REQ_BASE, analysisTypes: ['ast', 'bytecode'] });
    for (let i = 0; i < 100 && !astStarted; i++) {
      await new Promise((r) => setTimeout(r, 10));
    }
    expect(astStarted).toBe(true);

    const cancelled = await h.manager.cancel(REQ_BASE.requestId);
    expect(cancelled).toBe(true);
    releaseAst();

    // Second type must never be attempted.
    expect(attempted.length).toBe(0);
  }, 10_000);

  it('cancel on unknown request returns false without emitting', async () => {
    const h = makeManager({ binaryFound: true, analyzeImpl: async () => [] });
    expect(await h.manager.cancel('nope-0000001')).toBe(false);
    expect(h.events.length).toBe(0);
  });
});
