/**
 * AnalysisManager unit tests (plan todo 23 refactor): the manager is a thin
 * dispatcher — tests verify tracking/cancel/terminal-event responsibilities
 * against a FAKE registry whose adapter simulates per-type sequencing.
 */
import { describe, expect, it } from 'vitest';
import type {
  AnalysisEvent,
  AnalysisStartRequest,
  AnalysisType,
  EngineCapabilities
} from '@rh/protocol';
import { AnalysisManager } from './analysis-manager.js';
import type { AnalysisContext, EngineAdapter } from './engine-adapter.js';

const FULL_CAPS: EngineCapabilities = {
  astDump: true,
  bytecodeDump: true,
  optCodeDisasm: true,
  irGraphDump: true,
  deoptTrace: true,
  gcLog: true,
  profileSampling: true,
  perFunctionFilter: true,
  notes: []
};

interface Harness {
  events: AnalysisEvent[];
  manager: AnalysisManager;
}

function makeManager(
  adapterImpl: (req: AnalysisStartRequest, ctx: AnalysisContext) => Promise<void>
): Harness {
  const events: AnalysisEvent[] = [];
  const fakeAdapter: EngineAdapter = {
    id: 'd8-debug',
    describe: async () => ({
      id: 'd8-debug',
      version: '15.4.45',
      binaryPath: 'C:/fake/d8.exe',
      capabilities: FULL_CAPS,
      reason: null
    }),
    analyze: (req, ctx) => adapterImpl(req, ctx)
  };
  const registry = {
    getAdapter: (): EngineAdapter | null => fakeAdapter,
    analyze: async (req: AnalysisStartRequest, ctx: AnalysisContext): Promise<void> => {
      await fakeAdapter.analyze({ ...req, binaryPath: 'C:/fake/d8.exe' }, ctx);
    }
  };
  const manager = new AnalysisManager({
    registry: registry as never,
    emit: (e) => events.push(e)
  });
  return { events, manager };
}

const REQ: AnalysisStartRequest = {
  requestId: 'req-aaaaaaa1',
  engineId: 'd8-debug',
  code: 'function sum(){}',
  analysisTypes: ['bytecode']
};

describe('AnalysisManager (thin dispatcher)', () => {
  it('passes ctx through and clears tracking after done', async () => {
    const seenCtx: AnalysisContext[] = [];
    const h = makeManager(async (req, ctx) => {
      seenCtx.push(ctx);
      ctx.emit({
        t: 'result',
        requestId: req.requestId,
        result: {
          source: req.code,
          engine: 'v8',
          engineVersion: '15',
          analysisType: 'bytecode',
          rawOutput: '[generated bytecode]',
          artifacts: [],
          metadata: { flagsUsed: ['--print-bytecode'], durationMs: 1, binaryPath: 'b' }
        }
      });
      ctx.emit({ t: 'done', requestId: req.requestId });
    });

    await h.manager.start(REQ);
    expect(seenCtx.length).toBe(1);
    expect(h.events.filter((e) => e.t === 'result').length).toBe(1);
    expect(h.events.at(-1)?.t).toBe('done');
    // Cancel after completion must report false (tracking cleared).
    expect(await h.manager.cancel(REQ.requestId)).toBe(false);
  });

  it('cancel mid-run invokes registered kill-hook and emits cancelled', async () => {
    let killCalled = false;
    const h = makeManager(async (req, ctx) => {
      ctx.registerCancel(async () => {
        killCalled = true;
      });
      // Simulate a long engine run honouring cancellation.
      for (let i = 0; i < 100 && ctx.isLive(req.requestId); i++) {
        await new Promise((r) => setTimeout(r, 10));
      }
      ctx.emit({ t: 'done', requestId: req.requestId });
    });

    const running = h.manager.start(REQ);
    await new Promise((r) => setTimeout(r, 50));
    expect(await h.manager.cancel(REQ.requestId)).toBe(true);
    await running;

    expect(killCalled).toBe(true);
    expect(h.events.some((e) => e.t === 'cancelled')).toBe(true);
  }, 10_000);

  it('cancel on unknown request returns false without emitting', async () => {
    const h = makeManager(async () => {});
    expect(await h.manager.cancel('nope-0000001')).toBe(false);
    expect(h.events.length).toBe(0);
  });
});
