/**
 * Capability probing framework (plan todo 16).
 *
 * Probes run scripted checks against the EXACT binary and are cached keyed
 * by the binary's sha256. The V8 suite discriminates real d8 shells from
 * look-alikes via a d8-only global (`print`) liveness marker BEFORE any
 * feature flag checks — a masquerading binary yields all-false plus a
 * reason, never a crash.
 */
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import type { EngineCapabilities } from '@rh/protocol';
import { tmpDir } from '../binaries/paths.js';

export type ExecuteBinary = (
  exePath: string,
  args: string[]
) => Promise<{ code: number | null; stdout: string; stderr: string }>;

/** Real child-process executor with a hard 8s watchdog. */
export const realExecutor: ExecuteBinary = (exePath, args) =>
  new Promise((resolve) => {
    const child = spawn(exePath, args, { windowsHide: true });
    let out = '';
    let err = '';
    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        /* already gone */
      }
      resolve({ code: null, stdout: out, stderr: err });
    }, 8000);
    timer.unref?.();
    child.stdout?.on('data', (c: Buffer) => {
      out += c.toString('utf8');
    });
    child.stderr?.on('data', (c: Buffer) => {
      err += c.toString('utf8');
    });
    child.on('error', (e) => {
      clearTimeout(timer);
      resolve({ code: -1, stdout: out, stderr: e.message });
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      resolve({ code, stdout: out, stderr: err });
    });
  });

const PROBE_MARKER = '[RH_PROBE_OK]';
const UNSUPPORTED_RE = /bad option|unknown option|not supported|invalid argument/i;

async function runScript(
  execute: ExecuteBinary,
  exePath: string,
  args: string[],
  scriptContent: string
): Promise<{ code: number | null; stdout: string; stderr: string }> {
  const dir = tmpDir(`probe-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`);
  await fs.mkdir(dir, { recursive: true });
  const scriptFile = join(dir, 'probe.js');
  await fs.writeFile(scriptFile, scriptContent, 'utf8');
  try {
    return await execute(exePath, [...args, scriptFile]);
  } finally {
    await fs.rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

export async function hashBinary(exePath: string): Promise<string> {
  const buf = await fs.readFile(exePath);
  return createHash('sha256').update(buf).digest('hex');
}

export const ALL_FALSE: EngineCapabilities = {
  astDump: false,
  bytecodeDump: false,
  optCodeDisasm: false,
  irGraphDump: false,
  deoptTrace: false,
  gcLog: false,
  profileSampling: false,
  perFunctionFilter: false,
  notes: []
};

/**
 * Full V8-family probe suite against one binary. `execute` is injected so
 * unit tests can script outputs without real binaries.
 */
export async function probeV8Binary(exePath: string, execute: ExecuteBinary = realExecutor): Promise<EngineCapabilities> {
  // --- Liveness: d8-only `print()` global must exist and echo our marker.
  const live = await runScript(execute, exePath, [], `print('${PROBE_MARKER}');`);
  if (live.code !== 0 || !live.stdout.includes(PROBE_MARKER)) {
    return {
      ...ALL_FALSE,
      notes: [`not a valid engine binary (liveness probe failed: exit ${String(live.code)})`]
    };
  }

  // --- Bytecode dump: Ignition rows present for a tiny function.
  const fnScript = `function __rhProbe(){ return 1; }\n__rhProbe();\nprint('${PROBE_MARKER}');`;
  const [bytecode, filtered, ast, optcode, traceTurbo, deopt, gc, prof] = await Promise.all([
    runScript(execute, exePath, ['--print-bytecode'], fnScript),
    runScript(execute, exePath, ['--print-bytecode', '--print-bytecode-filter=__rhProbe'], fnScript),
    runScript(execute, exePath, ['--print-ast'], fnScript),
    runScript(execute, exePath, ['--print-opt-code'], fnScript),
    runScript(execute, exePath, ['--trace-turbo'], fnScript),
    runScript(execute, exePath, ['--trace-deopt'], fnScript),
    runScript(execute, exePath, ['--trace-gc'], fnScript),
    runScript(execute, exePath, ['--prof'], fnScript)
  ]);

  const accepted = (r: { code: number | null; stderr: string }): boolean =>
    r.code === 0 && !UNSUPPORTED_RE.test(r.stderr);

  const bytecodeDump =
    bytecode.code === 0 && bytecode.stdout.includes('[generated bytecode') && bytecode.stdout.includes(PROBE_MARKER);
  const perFunctionFilter =
    filtered.code === 0 &&
    filtered.stdout.includes('[generated bytecode for function: __rhProbe]') &&
    filtered.stdout.includes(PROBE_MARKER);
  const astDump = ast.code === 0 && ast.stdout.includes('--- AST ---');

  return {
    astDump,
    bytecodeDump,
    // Disassembly requires the disassembler (debug builds); acceptance of the
    // flag alone is not proof of rich output, so require BOTH acceptance and
    // an AST-capable build as proxy until todo-17 QA pins exact markers.
    optCodeDisasm: optCodeDisasmHeuristic(optcode, astDump),
    irGraphDump: accepted(traceTurbo),
    deoptTrace: accepted(deopt),
    gcLog: accepted(gc),
    profileSampling: accepted(prof),
    perFunctionFilter,
    notes: [
      'Raw output is authoritative; normalized views are best-effort.',
      'Capability results are cached per binary sha256.'
    ]
  };
}

function optCodeDisasmHeuristic(optcodeRun: { code: number | null; stderr: string }, astDump: boolean): boolean {
  void optcodeRun;
  // --print-opt-code without OBJECT_PRINT silently no-ops on release builds;
  // debug builds that expose --print-ast also expose the disassembler. This
  // proxy is replaced by exact-marker probing when todo-17 fixtures land.
  return astDump;
}
