/**
 * Probe framework + registry unit tests (plan todo 16).
 * All execution is injected — no real engines required here; the REAL
 * rel/dbg probes run network-gated in v8-engine.net.test.ts.
 */
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { EngineCapabilities } from '@rh/protocol';
import { probeV8Binary, type ExecuteBinary } from './probe.js';
import { EngineRegistry } from './registry.js';
import { executableName } from '../platform.js';

let dir = '';

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), 'rh-probe-'));
});

afterAll(async () => {
  await rm(dir, { recursive: true, force: true });
});

async function fakeBinary(name: string): Promise<string> {
  const p = join(dir, name);
  await writeFile(p, `binary:${name}`, 'utf8');
  return p;
}

/** Scripted d8: liveness OK, bytecode rows, filtered rows, but no AST (release-like). */
const releaseD8: ExecuteBinary = async (_exe, args) => {
  const script = args.at(-1) ?? '';
  const content = await import('node:fs/promises').then((fs) => fs.readFile(script, 'utf8'));
  if (!content.includes("print('[RH_PROBE_OK]');")) return { code: 1, stdout: '', stderr: 'no marker' };
  if (args.includes('--print-bytecode')) {
    if (args.includes('--print-bytecode-filter=__rhProbe')) {
      return { code: 0, stdout: '[generated bytecode for function: __rhProbe]\n[RH_PROBE_OK]', stderr: '' };
    }
    return { code: 0, stdout: '[generated bytecode for function: __rhProbe]\n[RH_PROBE_OK]', stderr: '' };
  }
  if (args.includes('--print-ast')) return { code: 0, stdout: '', stderr: '' }; // release: silent no-op
  return { code: 0, stdout: '[RH_PROBE_OK]', stderr: '' }; // flag-acceptance family
};

/** Scripted dbg build: everything the release lacks. */
const debugD8: ExecuteBinary = async (_exe, args) => {
  const base = await releaseD8(_exe, args);
  if (args.includes('--print-ast')) return { code: 0, stdout: '--- AST ---\nFUNC at 0', stderr: '' };
  return base;
};

/** Masquerader: accepts flags like node would, but has NO d8 print(). */
const masqueradingNode: ExecuteBinary = async (_exe, args) => {
  const script = args.at(-1) ?? '';
  const content = await import('node:fs/promises').then((fs) => fs.readFile(script, 'utf8'));
  if (content.includes('print(')) return { code: 1, stdout: '', stderr: 'ReferenceError: print is not defined' };
  return { code: 0, stdout: '', stderr: '' };
};

describe('probeV8Binary', () => {
  it('release d8: bytecode+filter true, ast false', async () => {
    const caps = await probeV8Binary(await fakeBinary('d8-rel.exe'), releaseD8);
    expect(caps.bytecodeDump).toBe(true);
    expect(caps.perFunctionFilter).toBe(true);
    expect(caps.astDump).toBe(false);
    expect(caps.deoptTrace).toBe(true);
  });

  it('debug d8: ast additionally true (and disasm proxy)', async () => {
    const caps = await probeV8Binary(await fakeBinary('d8-dbg.exe'), debugD8);
    expect(caps.bytecodeDump).toBe(true);
    expect(caps.astDump).toBe(true);
    expect(caps.optCodeDisasm).toBe(true);
  });

  it('masquerading binary → all false with explicit reason', async () => {
    const caps = await probeV8Binary(await fakeBinary('node.exe'), masqueradingNode);
    const expectedFalse = Object.entries(caps)
      .filter(([k]) => k !== 'notes')
      .every(([, v]) => v === false);
    expect(expectedFalse).toBe(true);
    expect(caps.notes.some((n) => n.includes('not a valid engine binary'))).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

function writeManifest(entries: Record<string, unknown>[]): Promise<void> {
  return import('node:fs/promises').then((fs) =>
    fs.writeFile(
      join(dir, 'manifest.json'),
      JSON.stringify({
        schemaVersion: 1,
        entries: entries.map((e) => ({
          license: 'BSD',
          source: 'official-canary',
          customBuildRequired: false,
          ...e
        }))
      }),
      'utf8'
    )
  );
}

describe('EngineRegistry', () => {
  it('describes installed engines with cached capabilities keyed by hash', async () => {
    process.env['RH_CACHE_ROOT'] = dir;
    await writeManifest([
      {
        kind: 'engine',
        id: 'd8-debug',
        platform: 'win64',
        arch: 'x64',
        version: '13.2.152.16',
        url: 'https://storage.googleapis.com/chromium-v8/official/canary/x.zip',
        sha256: 'a'.repeat(64),
        installedPath: dir
      }
    ]);
    // Point ENGINE_BINARY_NAME resolution at our fake binary file.
    await writeFile(join(dir, executableName('d8')), 'binary:d8-dbg', 'utf8');

    let executions = 0;
    const countingExecutor: ExecuteBinary = async (exe, args) => {
      executions += 1;
      return debugD8(exe, args);
    };
    const registry = new EngineRegistry({ execute: countingExecutor, hash: async () => 'fixed-hash' });

    const first = await registry.describe('d8-debug');
    expect(first.version).toBe('13.2.152.16');
    expect((first.capabilities as EngineCapabilities).astDump).toBe(true);

    const second = await registry.describe('d8-debug');
    expect(second.capabilities).toEqual(first.capabilities);
    expect(executions).toBe(9); // one full suite (liveness + 8 probes), then cache hit

    delete process.env['RH_CACHE_ROOT'];
  });

  it('reports missing engines with a reason and null capabilities', async () => {
    process.env['RH_CACHE_ROOT'] = join(dir, 'empty-cache');
    await import('node:fs/promises').then((fs) => fs.mkdir(join(dir, 'empty-cache'), { recursive: true }));
    const registry = new EngineRegistry({ execute: masqueradingNode });
    const desc = await registry.describe('spidermonkey');
    expect(desc.capabilities).toBeNull();
    expect(desc.reason).toContain('not installed');
    delete process.env['RH_CACHE_ROOT'];
  });
});
