/**
 * Compare-engines terminology mapping (plan todo 26, D4).
 * Lives in the engines layer so renderer never hardcodes engine internals;
 * exposed to the UI through a typed constant.
 */
import { z } from 'zod';

export const EngineTerminologySchema = z.object({
  id: z.string(),
  displayName: z.string(),
  bytecodeLabel: z.string(),
  astLabel: z.string().nullable(),
  optCodeLabel: z.string().nullable(),
  irGraphLabel: z.string().nullable(),
  deoptLabel: z.string().nullable(),
  gcLabel: z.string().nullable()
});
export type EngineTerminology = z.infer<typeof EngineTerminologySchema>;

export const ENGINE_TERMINOLOGY: Record<string, EngineTerminology> = {
  v8: {
    id: 'v8',
    displayName: 'V8',
    bytecodeLabel: 'Ignition bytecode',
    astLabel: 'AST (--print-ast)',
    optCodeLabel: 'Optimized code (TurboFan)',
    irGraphLabel: 'Turbolizer IR graph',
    deoptLabel: 'Deoptimization events',
    gcLabel: 'GC events'
  },
  spidermonkey: {
    id: 'spidermonkey',
    displayName: 'SpiderMonkey',
    bytecodeLabel: 'dis() bytecode + source notes',
    astLabel: 'Reflect.parse AST',
    optCodeLabel: null,
    irGraphLabel: null,
    deoptLabel: null,
    gcLabel: null
  },
  javascriptcore: {
    id: 'javascriptcore',
    displayName: 'JavaScriptCore',
    bytecodeLabel: 'LLInt / generated bytecode',
    astLabel: null,
    optCodeLabel: null,
    irGraphLabel: 'DFG/FTL graph dump',
    deoptLabel: 'OSR exit events',
    gcLabel: 'GC activity log'
  }
};

export function terminologyFor(engineId: string): EngineTerminology {
  return ENGINE_TERMINOLOGY[engineId] ?? {
    id: engineId,
    displayName: engineId,
    bytecodeLabel: 'bytecode',
    astLabel: null,
    optCodeLabel: null,
    irGraphLabel: null,
    deoptLabel: null,
    gcLabel: null
  };
}
