/**
 * V8EngineAdapter network integration (plan todo 17 QA happy).
 * Gated by RH_NET_TESTS=1. Runs the plan's canonical example against the
 * REAL downloaded d8-debug: `function sum(a,b){return a+b}` bytecode analysis
 * MUST contain '[generated bytecode for function: sum]'.
 */
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { installEngine } from '../binaries/engine-downloader.js';
import { CapabilityGateError, V8EngineAdapter } from './v8-adapter.js';
import { probeV8Binary } from './probe.js';

const RUN = process.env['RH_NET_TESTS'] === '1';

let dir = '';

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), 'rh-v8ad-net-'));
  process.env['RH_CACHE_ROOT'] = dir;
});

afterAll(() => {
  delete process.env['RH_CACHE_ROOT'];
});

describe.skipIf(!RUN)('V8 adapter on real d8-debug (network)', () => {
  it('bytecode analysis of sum() contains the generated-bytecode marker', async () => {
    const dbg = await installEngine({ engineId: 'd8-debug' });
    const binaryPath = join(dbg.entry.installedPath ?? '', 'd8.exe');

    const caps = await probeV8Binary(binaryPath);
    const adapter = new V8EngineAdapter({ capabilitiesOf: async () => caps });

    const results = await adapter.analyze({
      requestId: 'net-req-000001',
      binaryPath,
      code: 'function sum(a,b){ return a + b; }\nsum(1,2);',
      analysisTypes: ['bytecode'],
      functionName: 'sum',
      timeoutMs: 15_000
    });

    expect(results.length).toBe(1);
    // NOTE (format drift, discovered against REAL V8 15.x): headers now carry
    // a SharedFunctionInfo pointer after the name. The plan's literal marker
    // '[generated bytecode for function: sum]' matches only up to V8 ~12; we
    // assert the modern shape + a signature Ignition opcode instead.
    expect(results[0]?.rawOutput).toMatch(/generated bytecode for function: sum \(0x[0-9a-f]+ <SharedFunctionInfo sum>\)/);
    expect(results[0]?.rawOutput).toContain('Add ');
    expect(results[0]?.engineVersion).toMatch(/^\d+\.\d+/);
    expect(results[0]?.metadata.flagsUsed).toContain('--print-bytecode-filter=sum');
  }, 600_000);

  it('rejects optcode on release binaries before spawn (capability gate)', async () => {
    const rel = await installEngine({ engineId: 'v8' });
    const binaryPath = join(rel.entry.installedPath ?? '', 'd8.exe');
    const caps = await probeV8Binary(binaryPath);
    const adapter = new V8EngineAdapter({ capabilitiesOf: async () => caps });

    let calls = 0;
    try {
      await adapter.analyze({
        requestId: 'net-req-000002',
        binaryPath,
        code: 'function sum(){}',
        analysisTypes: ['optcode'],
        timeoutMs: 10_000
      });
      throw new Error('expected CapabilityGateError');
    } catch (err) {
      expect(err).toBeInstanceOf(CapabilityGateError);
    }
    void calls;
  }, 300_000);
});
