/**
 * V8EngineAdapter unit tests (plan todo 17): capability gating BEFORE spawn,
 * flag composition (incl. per-function filter), raw output policy, artifact
 * collection, timeout surfacing. Real-binary coverage is network-gated.
 */
import { mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { EngineCapabilities } from '@rh/protocol';
import { CapabilityGateError, V8EngineAdapter } from './v8-adapter.js';

let dir = '';

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), 'rh-v8ad-'));
});

afterAll(async () => {
  await rm(dir, { recursive: true, force: true });
});

const FULL_CAPS: EngineCapabilities = {
  astDump: true,
  bytecodeDump: true,
  optCodeDisasm: true,
  irGraphDump: true,
  deoptTrace: true,
  gcLog: true,
  profileSampling: true,
  perFunctionFilter: true,
  notes: []
};

const REL_CAPS: EngineCapabilities = { ...FULL_CAPS, astDump: false, optCodeDisasm: false };

function makeAdapter(caps: EngineCapabilities) {
  const calls: { exePath: string; args: string[]; cwd: string }[] = [];
  const adapter = new V8EngineAdapter({
    capabilitiesOf: async () => caps,
    execute: async () => ({ code: 0, stdout: 'V8 version 13.2.152.16\n', stderr: '' }),
    runIsolated: async (options) => {
      calls.push({ exePath: options.exePath, args: options.args, cwd: options.cwd });
      return { code: 0, stdout: `[generated bytecode for function: sum]\n[RH_PROBE_OK]`, stderr: '', timedOut: false };
    }
  });
  return { adapter, calls };
}

const BASE_REQ = {
  requestId: 'req-12345678',
  binaryPath: join(dir, 'd8.exe'),
  timeoutMs: 5000
};

describe('V8EngineAdapter', () => {
  it('gates capabilities BEFORE spawning (optcode on release binary)', async () => {
    const { adapter, calls } = makeAdapter(REL_CAPS);
    await expect(
      adapter.analyze({ ...BASE_REQ, code: 'function sum(){}', analysisTypes: ['optcode'] })
    ).rejects.toThrow(CapabilityGateError);
    expect(calls.length).toBe(0); // no wasted process
  });

  it('bytecode analysis applies per-function filter when available', async () => {
    const { adapter, calls } = makeAdapter(FULL_CAPS);
    const results = await adapter.analyze({
      ...BASE_REQ,
      code: 'function sum(a,b){return a+b}; sum(1,2);',
      analysisTypes: ['bytecode'],
      functionName: 'sum'
    });
    expect(results.length).toBe(1);
    expect(results[0]?.metadata.flagsUsed).toContain('--no-lazy');
    expect(results[0]?.rawOutput).toContain('[generated bytecode for function: sum]');
    expect(results[0]?.engine).toBe('v8');
    // Snippet written to an isolated work dir and passed as the LAST arg.
    const snippetPath = calls[0]!.args.at(-1) ?? '';
    const snippet = await readFile(snippetPath, 'utf8');
    expect(snippet).toContain('function sum');
  });

  it('omits the filter flag when perFunctionFilter is unavailable', async () => {
    const { adapter, calls } = makeAdapter({ ...REL_CAPS, bytecodeDump: true, perFunctionFilter: false });
    await adapter.analyze({
      ...BASE_REQ,
      code: 'function sum(){}',
      analysisTypes: ['bytecode'],
      functionName: 'sum'
    });
    expect(calls[0]?.args.some((a) => a.startsWith('--print-bytecode-filter='))).toBe(false);
  });

  it('collects turbo JSON artifacts from the isolated work directory', async () => {
    const { adapter } = makeAdapter(FULL_CAPS);
    let workDirAtCall = '';
    const adapterWithArtifacts = new V8EngineAdapter({
      capabilitiesOf: async () => FULL_CAPS,
      runIsolated: async (options) => {
        workDirAtCall = options.cwd;
        // Simulate d8 writing turbolizer artifacts next to the snippet.
        await writeFile(join(options.cwd, 'turbo-0x1.json'), '{"fun":"sum"}', 'utf8');
        await writeFile(join(options.cwd, 'turbo.cfg'), '', 'utf8');
        return { code: 0, stdout: '', stderr: '', timedOut: false };
      }
    });
    const results = await adapterWithArtifacts.analyze({
      ...BASE_REQ,
      code: 'function sum(){}',
      analysisTypes: ['ir-graph']
    });
    expect(results[0]?.artifacts.map((a) => a.name)).toEqual(['turbo-0x1.json', 'turbo.cfg']);
    void workDirAtCall;
    // Flags direct artifacts into the SAME directory we later scan.
    const flags = results[0]?.metadata.flagsUsed ?? [];
    expect(flags.some((f) => f.startsWith(`--trace-turbo-path=`))).toBe(true);
    void adapter;
  });

  it('surfaces timeouts inside rawOutput with labeled marker', async () => {
    const adapter = new V8EngineAdapter({
      capabilitiesOf: async () => FULL_CAPS,
      runIsolated: async () => ({ code: null, stdout: '', stderr: '', timedOut: true })
    });
    const results = await adapter.analyze({
      ...BASE_REQ,
      code: 'while(true){}',
      analysisTypes: ['gc']
    });
    expect(results[0]?.rawOutput).toContain('analysis timed out');
  });

  it('appends non-empty stderr under a labeled separator (verbatim policy)', async () => {
    const adapter = new V8EngineAdapter({
      capabilitiesOf: async () => FULL_CAPS,
      runIsolated: async () => ({ code: 0, stdout: 'OUT', stderr: 'ERR-TAIL', timedOut: false })
    });
    const results = await adapter.analyze({ ...BASE_REQ, code: '1;', analysisTypes: ['deopts'] });
    expect(results[0]?.rawOutput.startsWith('OUT')).toBe(true);
    expect(results[0]?.rawOutput).toContain('[stderr]\nERR-TAIL');
  });

  it('parses engine version via injected executor', async () => {
    const adapter = new V8EngineAdapter({
      capabilitiesOf: async () => FULL_CAPS,
      execute: async () => ({ code: 0, stdout: 'V8 version 13.2.152.16\n', stderr: '' })
    });
    const version = await adapter.engineVersion('C:/fake/d8.exe');
    expect(version).toBe('13.2.152.16');

    const malformed = new V8EngineAdapter({
      capabilitiesOf: async () => FULL_CAPS,
      execute: async () => ({ code: 0, stdout: 'garbage', stderr: '' })
    });
    const fallback = await malformed.engineVersion('C:/fake/d8.exe');
    expect(fallback.startsWith('unknown')).toBe(true);
  });

  it('work dirs are unique per request (no cross-run clobbering)', async () => {
    const seenCwd: string[] = [];
    const adapter = new V8EngineAdapter({
      capabilitiesOf: async () => FULL_CAPS,
      runIsolated: async (options) => {
        seenCwd.push(options.cwd);
        return { code: 0, stdout: '', stderr: '', timedOut: false };
      }
    });
    await adapter.analyze({ ...BASE_REQ, code: '1;', analysisTypes: ['gc'] });
    await adapter.analyze({ ...BASE_REQ, code: '2;', analysisTypes: ['gc'] });
    expect(new Set(seenCwd).size).toBe(2);
    expect(await readdir(seenCwd[0]!)).toContain('snippet.mjs');
  });
});
