/**
 * Wrapping strategies network integration (plan todo 20 QA).
 * Gated by RH_NET_TESTS=1. Happy: bare expression `users.filter(...)` with
 * `users` defined above в†’ wrapped standalone snippet produces bytecode for
 * the filter callback + repr output. Failure: selection referencing an
 * undefined identifier в†’ ReferenceError surfaced in rawOutput, no crash.
 */
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { installEngine } from '../binaries/engine-downloader.js';
import { V8EngineAdapter } from './v8-adapter.js';
import { probeV8Binary } from './probe.js';

const RUN = process.env['RH_NET_TESTS'] === '1';

let dir = '';
let d8Path: string | null = null;

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), 'rh-wrap-net-'));
  process.env['RH_CACHE_ROOT'] = dir;
});

afterAll(() => {
  delete process.env['RH_CACHE_ROOT'];
});

/** Install once per file; both tests share the binary. */
async function getD8(): Promise<string> {
  if (d8Path !== null) return d8Path;
  const dbg = await installEngine({ engineId: 'd8-debug' });
  d8Path = join(dbg.entry.installedPath ?? '', 'd8.exe');
  return d8Path;
}

const USERS_PRELUDE = [
  "const users = [{ id: 1, name: 'Alex', active: true }, { id: 2, name: 'Sam', active: false }];"
].join('\n');

describe.skipIf(!RUN)('selection wrapping on real d8-debug (network)', () => {
  it('wrapped bare expression runs standalone and prints repr', async () => {
    const binaryPath = await getD8();
    const caps = await probeV8Binary(binaryPath);
    const adapter = new V8EngineAdapter({ capabilitiesOf: async () => caps });

    // EXACTLY what buildAnalysisSnippet emits for kind=expression.
    const selection = 'users.filter((u) => u.active)';
    const wrapped = `${USERS_PRELUDE}\n__rh_out(__rh_repr(${selection}));`;
    const harness = [
      "const __rh_repr = (v) => { if (Array.isArray(v)) return '[' + v.map((u) => u && u.name).join(', ') + ']'; return String(v); };",
      "const __rh_out = (s) => { if (typeof print === 'function') print(s); else console.log(s); };",
      wrapped
    ].join('\n');

    const results = await adapter.analyze({
      requestId: 'wrap-net-000001',
      binaryPath,
      code: harness,
      analysisTypes: ['bytecode'],
      timeoutMs: 15_000
    });

    expect(results.length).toBe(1);
    // Anonymous callbacks dump under empty-name headers in V8 15.x; assert
    // multiple compiled blocks + the filter property load + runtime repr.
    const blocks = results[0]?.rawOutput.match(/generated bytecode for function/g) ?? [];
    expect(blocks.length).toBeGreaterThanOrEqual(2);
    expect(results[0]?.rawOutput).toContain('"filter"');
    expect(results[0]?.rawOutput).toContain('[Alex]');
  }, 600_000);

  it('undefined identifier surfaces ReferenceError in rawOutput without crashing', async () => {
    const binaryPath = await getD8();
    const caps = await probeV8Binary(binaryPath);
    const adapter = new V8EngineAdapter({ capabilitiesOf: async () => caps });

    const results = await adapter.analyze({
      requestId: 'wrap-net-000002',
      binaryPath,
      code: "__rh_out(__rh_repr(users.filter((x) => x.active)));",
      analysisTypes: ['bytecode'],
      timeoutMs: 15_000
    });

    expect(results.length).toBe(1);
    expect(results[0]?.rawOutput).toContain('ReferenceError');
    // Analysis-of-broken-snippet is an expected outcome, not an app failure.
    expect(results[0]?.metadata.durationMs).toBeGreaterThanOrEqual(0);
  }, 300_000);
});
